name: Mutation testing

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        name: Infection
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  coverage: pcov
                  tools: composer:v2
                  ini-file: development

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest
                  composer-options: --prefer-dist --prefer-stable

            - name: Run tests with PHPUnit
              run: vendor/bin/phpunit --coverage-xml=build/coverage/coverage-xml --log-junit=build/coverage/junit.xml

            - name: Run Infection
              env:
                  INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
              run: vendor/bin/infection --threads=4 --skip-initial-tests --coverage=build/coverage --no-progress --log-verbosity=none --show-mutations
